name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install third-party apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential cmake
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      working-directory: /tmp/   
    - name: Build and Test on Linux
      run: |
        ./compile_source_code.sh -CMakeToolchainFile /tmp/vcpkg/scripts/buildsystems/vcpkg.cmake -RunTests
      working-directory: ./devops/scripts/bash/

  build_windows:
    runs-on: windows-latest
    needs: [build_and_test_ubuntu]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install third-party choco dependencies
      run: |
        choco install cmake

    - name: Install vcpkg
      run: |
        cd $env:TEMP
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat 

    - name: Build on Windows
      shell: pwsh
      run: |
        .\compile_source_code.ps1 -CMakeToolchainFile $env:TEMP\vcpkg\scripts\buildsystems\vcpkg.cmake
      working-directory: .\devops\scripts\ps1\
  
  build_macos:
    runs-on: macos-latest
    needs: [build_and_test_ubuntu]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install third-party brew dependencies
      run: |
        brew install pkg-config cmake
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      working-directory: /tmp/
    - name: Build on macOS
      run: |
        ./compile_source_code.sh -CMakeToolchainFile /tmp/vcpkg/scripts/buildsystems/vcpkg.cmake
      working-directory: ./devops/scripts/bash/
